export const SAVE_INSTITUTION = 'SAVE_INSTITUTION';
export const SELECT_INSTITUTION = 'SELECT_INSTITUTION';
export const REMOVE_INSTITUTION = 'REMOVE_INSTITUTION';
export const REMOVE_ALL_INSTITUTIONS = 'REMOVE_ALL_INSTITUTIONS';
export const SAVE_USER = 'SAVE_USER';
export const REMOVE_ALL_USERS = 'REMOVE_ALL_USERS';
export const SET_LOGGED_USER = 'SET_LOGGED_USER';
