// Institution
export const SAVE_INSTITUTION = 'SAVE_INSTITUTION';
export const UPDATE_INSTITUTION = 'UPDATE_INSTITUTION';
export const SELECT_INSTITUTION = 'SELECT_INSTITUTION';
export const REMOVE_INSTITUTION = 'REMOVE_INSTITUTION';
export const REMOVE_ALL_INSTITUTIONS = 'REMOVE_ALL_INSTITUTIONS';
export const SAVE_GRADE_TO_INSTITUTION = 'ADD_GRADE_TO_INSTITUTION';
export const SAVE_USERS_TO_INSTITUTION = 'SAVE_USERS_TO_INSTITUTION';
export const REMOVE_USER_FROM_INSTITUION = 'REMOVE_USER_FROM_INSTITUION';
// User
export const SAVE_USER = 'SAVE_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const SET_LOGGED_USER = 'SET_LOGGED_USER';
export const REMOVE_ALL_USERS = 'REMOVE_ALL_USERS';
// Grade
export const SAVE_GRADE = 'SAVE_GRADE';
export const SELECT_GRADE = 'SELECT_GRADE';
export const REMOVE_ALL_GRADES = 'REMOVE_ALL_GRADES';
export const SAVE_SUBJECT_TO_GRADE = 'SAVE_SUBJECT_TO_GRADE';
// Subject
export const SAVE_SUBJECT = 'SAVE_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const REMOVE_ALL_SUBJECTS = 'REMOVE_ALL_SUBJECTS';
export const ADD_TEACHER_TO_SUBJECT = 'ADD_TEACHER_TO_SUBJECT';
export const ADD_STUDENT_TO_SUBJECT = 'ADD_STUDENT_TO_SUBJECT';
export const ADD_DISCUSSION_TO_SUBJECT = 'ADD_DISCUSSION_TO_SUBJECT';
// Discussion
export const SAVE_DISCUSSION = 'SAVE_DISCUSSION';
export const ADD_REPLY_TO_DISCUSSION = 'ADD_REPLY_TO_DISCUSSION';
export const REMOVE_ALL_DISCUSSIONS = 'REMOVE_ALL_DISCUSSIONS';
// Reply
export const SAVE_REPLY = 'SAVE_REPLY';
export const ADD_REPLY_TO_REPLY = 'ADD_REPLY_TO_REPLY';
export const REMOVE_ALL_REPLIES = 'REMOVE_ALL_REPLIES';
