export const userRoles = {
  TEACHER: 'TEACHER',
  STUDENT: 'STUDENT',
  ADMIN: 'ADMIN',
};

export const emailType = {
  TO_ALL_STUDENTS: 'TO_ALL_STUDENTS',
  TO_ALL_TEACHERS: 'TO_ALL_TEACHERS',
  TO_ALL_GRADE_STUDENTS: 'TO_ALL_GRADE_STUDENTS',
  TO_ALL_SUBJECT_STUDENTS: 'TO_ALL_SUBJECT_STUDENTS',
};

export default {};
